name: Build PWA APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java and Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Bubblewrap (non-interactive)
      run: |
        npm install -g @bubblewrap/cli
        bubblewrap --version

    - name: Prepare environment
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        echo "y" | sdkmanager --licenses

    - name: Build APK
      run: |
        mkdir -p ./pwa-build
        cd ./pwa-build
        bubblewrap init --manifest=https://${{ github.repository_owner }}.github.io/faq/manifest.json \
          --jdkPath=/usr/lib/jvm/zulu17-jdk-amd64 \
          --androidSdkPath=$ANDROID_HOME \
          --default
        bubblewrap build --skipPwaValidation --skipVersionCheck
        
        if [ -f "app-release.apk" ]; then
          mv app-release.apk ../pwa-app.apk
          echo "APK gerado com sucesso!"
          ls -lh ../pwa-app.apk
        else
          echo "::error::Falha na geração do APK"
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pwa-apk
        path: pwa-app.apk
