name: Build PWA APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java (JDK 17)
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install Bubblewrap (sem interação)
      run: |
        npm install -g @bubblewrap/cli
        echo -e "y\ny" | bubblewrap --version  # Responde automaticamente aos prompts

    - name: Build APK (modo não interativo)
      run: |
        mkdir -p ./pwa-build
        cd ./pwa-build
        echo -e "y\nn" | bubblewrap init --manifest=https://${{ github.repository_owner }}.github.io/faq/manifest.json
        bubblewrap build --skipPwaValidation --skipVersionCheck
        
        if [ -f "app-release.apk" ]; then
          mv app-release.apk ../pwa-app.apk
          echo "APK gerado com sucesso!"
          ls -lh ../pwa-app.apk
        else
          echo "::error::Falha na geração do APK"
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pwa-apk
        path: pwa-app.apk
