name: Build PWA APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java (JDK 17)
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install Android Command Line Tools
      run: |
        mkdir -p ~/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d ~/android-sdk/cmdline-tools
        mv ~/android-sdk/cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest
        echo "ANDROID_HOME=~/android-sdk" >> $GITHUB_ENV
        echo "PATH=~/android-sdk/cmdline-tools/latest/bin:~/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Accept Android Licenses
      run: |
        yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install Android Packages
      run: |
        ~/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

    - name: Install Bubblewrap Non-Interactive
      run: |
        npm install -g @bubblewrap/cli
        echo "Bubblewrap version: $(bubblewrap --version)"

    - name: Build APK
      run: |
        mkdir -p ./pwa-build
        cd ./pwa-build
        echo -e "n\nn" | bubblewrap init \
          --manifest=https://${{ github.repository_owner }}.github.io/faq/manifest.json \
          --jdkPath=/usr/lib/jvm/zulu17-jdk-amd64 \
          --androidSdkPath=~/android-sdk \
          --default
        
        bubblewrap build --skipPwaValidation --skipVersionCheck
        
        if [ -f "app-release.apk" ]; then
          mv app-release.apk ../pwa-app.apk
          echo "APK gerado com sucesso!"
          ls -lh ../pwa-app.apk
        else
          echo "::error::Falha na geração do APK"
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pwa-apk
        path: pwa-app.apk
