name: Build PWA APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y nodejs npm default-jdk
        npm install -g @bubblewrap/cli

    - name: Debug - Verify URLs
      run: |
        echo "Verificando URLs essenciais:"
        curl -I https://${{ github.repository_owner }}.github.io/faq/manifest.json
        curl -I https://${{ github.repository_owner }}.github.io/faq/
        curl -I https://${{ github.repository_owner }}.github.io/.well-known/assetlinks.json

    - name: Build APK (método garantido)
      run: |
        # Cria diretório temporário
        mkdir -p ./pwa-build
        cd ./pwa-build
        
        # Gera APK com fallbacks
        bubblewrap init --manifest=https://${{ github.repository_owner }}.github.io/faq/manifest.json || \
        bubblewrap init --manifest=https://${{ github.repository_owner }}.github.io/faq/manifest.json --default
        
        bubblewrap build --skipPwaValidation --skipSigning
        
        # Move o APK para a raiz
        mv ./app-release.apk ../pwa-app.apk
        
        # Verificação final
        if [ -f "../pwa-app.apk" ]; then
          echo "APK gerado com sucesso!"
          ls -lh ../pwa-app.apk
        else
          echo "::error::Falha crítica - APK não gerado"
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pwa-apk
        path: pwa-app.apk
        if-no-files-found: error
