name: Build PWA APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Previne timeout precoce

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Bubblewrap
      run: |
        npm install -g @bubblewrap/cli
        
    - name: Generate APK
      run: |
        # Verifica se o manifest está acessível
        curl -s https://${{ github.repository_owner }}.github.io/faq/manifest.json || exit 1
        
        # Gera APK com timeout
        timeout 300s bubblewrap init --manifest=https://${{ github.repository_owner }}.github.io/faq/manifest.json --directory=./pwa-build || exit 0
        cd pwa-build
        timeout 300s bubblewrap build || exit 0
        [ -f app-release.apk ] && mv app-release.apk ../pwa-app.apk || exit 1

    - name: Upload APK
      if: success() || failure()  # Executa mesmo com falha parcial
      uses: actions/upload-artifact@v4
      with:
        name: pwa-apk
        path: pwa-app.apk
        retention-days: 1
