name: Build PWA APK - Solução Final Não-Interativa

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java and Android
      uses: android-actions/setup-android@v3

    - name: Install Bubblewrap
      run: |
        npm install -g @bubblewrap/cli@1.9.0 --no-fund --no-audit --silent
        mkdir -p ~/.bubblewrap
        echo '{"analyticsEnabled": false, "nonInteractive": true}' > ~/.bubblewrap/config.json

    - name: Generate and Build APK
      run: |
        # Cria diretório para o build
        mkdir -p ./pwa-build
        cd ./pwa-build
        
        # Gera o projeto diretamente sem arquivo de configuração separado
        bubblewrap init \
          --manifest=https://avariado.github.io/faq/manifest.json \
          --packageId=com.pwa.faq \
          --host=avariado.github.io \
          --path=/faq/ \
          --appVersionName=1.0.0 \
          --appVersionCode=1 \
          --enableNotifications=false \
          --display=standalone \
          --jdkPath=$JAVA_HOME \
          --androidSdkPath=$ANDROID_HOME \
          --default \
          --non-interactive
        
        # Constrói o APK
        bubblewrap build \
          --skipPwaValidation \
          --skipVersionCheck \
          --skipSigning
        
        if [ -f "app-release-unsigned.apk" ]; then
          mv app-release-unsigned.apk ../pwa-app.apk
          echo "✅ APK gerado com sucesso!"
          ls -lh ../pwa-app.apk
        else
          echo "::error::❌ Falha na geração do APK"
          bubblewrap doctor
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pwa-apk
        path: pwa-app.apk
