name: Build PWA APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java (requerido pelo Bubblewrap)
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Build APK with Bubblewrap (método direto)
      run: |
        # Instalação limpa do Bubblewrap
        npm install -g @bubblewrap/cli --no-package-lock --no-save
        
        # Geração direta do APK (sem init)
        bubblewrap build --manifest=https://${{ github.repository_owner }}.github.io/faq/manifest.json
        
        # Verificação do arquivo gerado
        ls -lh ./app-release.apk || echo "::error::APK não foi gerado"

    - uses: actions/upload-artifact@v3
      with:
        name: pwa-apk
        path: app-release.apk
