name: Build PWA APK - Solução Completa 2025

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java and Android
      uses: android-actions/setup-android@v3

    - name: Install Bubblewrap (Non-Interactive)
      run: |
        npm install -g @bubblewrap/cli@1.9.0 --no-fund --no-audit --silent
        mkdir -p ~/.bubblewrap
        echo '{"analyticsEnabled": false, "nonInteractive": true}' > ~/.bubblewrap/config.json

    - name: Generate Auto-Response File
      run: |
        mkdir -p ./pwa-build
        # Cria arquivo com todas as respostas necessárias
        echo -e "avariado.github.io\n/faq/\nn\nn\nn" > ./pwa-build/responses.txt

    - name: Build APK (Forced Non-Interactive)
      run: |
        cd ./pwa-build
        # Pipe das respostas automáticas para o bubblewrap
        cat responses.txt | bubblewrap init \
          --manifest=https://avariado.github.io/faq/manifest.json \
          --jdkPath=$JAVA_HOME \
          --androidSdkPath=$ANDROID_HOME \
          --default
        
        bubblewrap build \
          --skipPwaValidation \
          --skipVersionCheck \
          --skipSigning
        
        if [ -f "app-release-unsigned.apk" ]; then
          mv app-release-unsigned.apk ../pwa-app.apk
          echo "✅ APK gerado com sucesso!"
          ls -lh ../pwa-app.apk
        else
          echo "::error::❌ Falha na geração do APK"
          bubblewrap doctor
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pwa-apk
        path: pwa-app.apk
