name: Build PWA APK - Versão Funcionando

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        check-latest: true

    - name: Setup Java and Android
      uses: android-actions/setup-android@v3

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git python3 make g++

    - name: Install Bubblewrap (Stable Version)
      run: |
        npm install -g @bubblewrap/cli@1.20.0 --no-fund --no-audit --silent
        mkdir -p ~/.bubblewrap
        echo '{"analyticsEnabled": false, "nonInteractive": true}' > ~/.bubblewrap/config.json

    - name: Verify Installation
      run: |
        echo "Node version: $(node -v)"
        echo "npm version: $(npm -v)"
        echo "Bubblewrap version: $(bubblewrap --version)"
        if ! command -v bubblewrap &> /dev/null; then
          echo "::error::Bubblewrap não está instalado corretamente"
          exit 1
        fi

    - name: Generate APK
      run: |
        mkdir -p ./pwa-output
        cd ./pwa-output
        
        bubblewrap init \
          --manifest="https://avariado.github.io/faq/manifest.json" \
          --packageId="com.pwa.faq" \
          --host="avariado.github.io" \
          --path="/faq/" \
          --appVersionName="1.0.0" \
          --appVersionCode=1 \
          --enableNotifications=false \
          --display="standalone" \
          --default \
          --non-interactive
        
        bubblewrap build \
          --skipPwaValidation \
          --skipVersionCheck \
          --skipSigning

        if [ -f "app-release-unsigned.apk" ]; then
          mv app-release-unsigned.apk ../pwa-app.apk
          echo "✅ APK gerado com sucesso!"
          ls -lh ../pwa-app.apk
        else
          echo "::error::❌ Falha na geração do APK"
          echo "Verificando logs..."
          cat ~/.bubblewrap/logs/*
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pwa-apk
        path: pwa-app.apk
