name: Build PWA APK - Solução Garantida

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Setup Java and Android
      uses: android-actions/setup-android@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl git
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
        npm install -g npm@latest

    - name: Install Bubblewrap (Approach 1)
      id: bubblewrap
      continue-on-error: true
      run: |
        npm install -g @bubblewrap/cli@1.19.0 --no-fund --no-audit --silent
        mkdir -p ~/.bubblewrap
        echo '{"analyticsEnabled": false, "nonInteractive": true}' > ~/.bubblewrap/config.json

    - name: Install Bubblewrap (Approach 2 - Fallback)
      if: steps.bubblewrap.outcome == 'failure'
      run: |
        sudo npm install -g @bubblewrap/cli@1.19.0 --no-fund --no-audit --unsafe-perm
        mkdir -p ~/.bubblewrap
        echo '{"analyticsEnabled": false, "nonInteractive": true}' > ~/.bubblewrap/config.json

    - name: Verify Installation
      run: |
        bubblewrap --version || (echo "::error::Bubblewrap installation failed" && exit 1)

    - name: Generate APK
      run: |
        mkdir -p ./pwa-output
        cd ./pwa-output
        
        bubblewrap init \
          --manifest="https://avariado.github.io/faq/manifest.json" \
          --packageId="com.pwa.faq" \
          --host="avariado.github.io" \
          --path="/faq/" \
          --appVersionName="1.0.0" \
          --appVersionCode=1 \
          --enableNotifications=false \
          --display="standalone" \
          --default \
          --non-interactive
        
        bubblewrap build \
          --skipPwaValidation \
          --skipVersionCheck \
          --skipSigning

        if [ -f "app-release-unsigned.apk" ]; then
          mv app-release-unsigned.apk ../pwa-app.apk
          echo "✅ APK generated successfully!"
          ls -lh ../pwa-app.apk
        else
          echo "::error::❌ Critical failure - APK not generated"
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pwa-apk
        path: pwa-app.apk
