name: Build PWA APK - Solução Definitiva

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java and Android
      uses: android-actions/setup-android@v3

    - name: Install Bubblewrap
      run: |
        npm install -g @bubblewrap/cli@1.19.0 --no-fund --no-audit --silent
        mkdir -p ~/.bubblewrap
        echo '{"analyticsEnabled": false, "nonInteractive": true}' > ~/.bubblewrap/config.json

    - name: Generate APK
      run: |
        # Cria diretório temporário
        mkdir -p ./pwa-temp
        cd ./pwa-temp
        
        # Comando DIRETO sem arquivos de configuração
        bubblewrap init \
          --manifest="https://avariado.github.io/faq/manifest.json" \
          --packageId="com.pwa.faq" \
          --host="avariado.github.io" \
          --path="/faq/" \
          --appVersionName="1.0.0" \
          --appVersionCode=1 \
          --enableNotifications=false \
          --display="standalone" \
          --default \
          --non-interactive
        
        # Build do APK (modo silencioso)
        bubblewrap build \
          --skipPwaValidation \
          --skipVersionCheck \
          --skipSigning > /dev/null 2>&1
        
        # Verifica e move o APK
        if [ -f "app-release-unsigned.apk" ]; then
          mv app-release-unsigned.apk ../pwa-app.apk
          echo "✅ APK gerado com sucesso!"
          ls -lh ../pwa-app.apk
        else
          echo "::error::❌ Falha crítica - APK não gerado"
          echo "Últimos logs:"
          cat ~/.bubblewrap/logs/*
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pwa-apk
        path: pwa-app.apk
