name: Build PWA APK

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install Bubblewrap
      run: |
        npm install -g @bubblewrap/cli --no-package-lock --no-save
        bubblewrap --version

    - name: Build APK
      run: |
        bubblewrap build --manifest=https://${{ github.repository_owner }}.github.io/faq/manifest.json
        ls -lh ./app-release.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pwa-apk
        path: app-release.apk
        retention-days: 1
