name: Build PWA APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Atualizado para v4

    - name: Set up Node.js
      uses: actions/setup-node@v4  # Atualizado para v4
      with:
        node-version: 20  # Versão mais recente do Node

    - name: Install dependencies
      run: |
        npm install -g @bubblewrap/cli

    - name: Generate APK with Bubblewrap
      run: |
        bubblewrap init --manifest=https://${{ github.repository_owner }}.github.io/faq/manifest.json --directory=./pwa-build
        cd pwa-build
        bubblewrap build
        mv ./app-release.apk ../pwa-app.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4  # Atualizado para v4
      with:
        name: pwa-apk
        path: pwa-app.apk
