name: Build PWA APK - Ultimate Solution

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java (JDK 17)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Android Command Line Tools
      run: |
        mkdir -p ~/android-sdk/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d ~/android-sdk/cmdline-tools
        mv ~/android-sdk/cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Accept Android Licenses
      run: |
        yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses >/dev/null

    - name: Install Android Packages
      run: |
        ~/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

    - name: Install Bubblewrap
      run: |
        npm install -g @bubblewrap/cli@1.9.0
        echo "Bubblewrap version: $(bubblewrap --version)"

    - name: Build APK
      run: |
        mkdir -p ./pwa-build
        cd ./pwa-build
        
        # Força modo não interativo
        echo -e "n\nn" | bubblewrap init \
          --manifest=https://${{ github.repository_owner }}.github.io/faq/manifest.json \
          --jdkPath=$JAVA_HOME \
          --androidSdkPath=$ANDROID_HOME \
          --default
        
        bubblewrap build \
          --skipPwaValidation \
          --skipVersionCheck \
          --skipSigning
        
        if [ -f "app-release-unsigned.apk" ]; then
          mv app-release-unsigned.apk ../pwa-app.apk
          echo "APK gerado com sucesso!"
          ls -lh ../pwa-app.apk
        else
          echo "::error::Falha na geração do APK"
          ls -la
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pwa-apk
        path: pwa-app.apk
