name: Build PWA APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Create minimal package.json
      run: |
        echo '{
          "name": "pwa-builder",
          "version": "1.0.0",
          "private": true,
          "dependencies": {}
        }' > package.json
        npm install @bubblewrap/cli --save-dev

    - name: Verify manifest access
      run: |
        curl -s https://${{ github.repository_owner }}.github.io/faq/manifest.json > manifest.json
        if [ ! -s manifest.json ]; then
          echo "::error::Manifest não encontrado ou vazio!"
          exit 1
        fi

    - name: Generate APK
      run: |
        npx bubblewrap init --manifest=https://${{ github.repository_owner }}.github.io/faq/manifest.json
        npx bubblewrap build
        ls -la ./app-release.apk || echo "::warning::APK não gerado!"

    - name: Rename and upload APK
      run: |
        if [ -f "./app-release.apk" ]; then
          mv ./app-release.apk ./pwa-app.apk
          echo "APK renomeado com sucesso!"
        else
          echo "::error::Arquivo APK não encontrado!"
          exit 1
        fi

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: pwa-apk
        path: pwa-app.apk
        if-no-files-found: error
