name: Build PWA APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Create package structure
      run: |
        # Cria package.json mínimo
        echo '{
          "name": "pwa-builder",
          "version": "1.0.0",
          "private": true,
          "dependencies": {
            "@bubblewrap/cli": "^1.0.0"
          }
        }' > package.json
        
        # Gera lock file
        npm install --package-lock-only
        
        # Lista arquivos para verificação
        ls -la

    - name: Install Bubblewrap
      run: npm install

    - name: Generate APK
      run: |
        npx bubblewrap init --manifest=https://${{ github.repository_owner }}.github.io/faq/manifest.json
        npx bubblewrap build
        
        # Verifica se o APK foi gerado
        if [ ! -f "./app-release.apk" ]; then
          echo "::error::Falha ao gerar APK"
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pwa-apk
        path: app-release.apk
