name: Build PWA APK Nuclear Option

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Environment
      run: |
        # Instala todas as dependências necessárias
        sudo apt-get update
        sudo apt-get install -y wget unzip zip
        
        # JDK 17 (Zulu)
        wget -qO - https://apt.corretto.aws/corretto.key | sudo apt-key add - 
        sudo add-apt-repository 'deb https://apt.corretto.aws stable main'
        sudo apt-get update
        sudo apt-get install -y zulu17-jdk
        
        # Android SDK
        mkdir -p ~/android-sdk/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d ~/android-sdk/cmdline-tools
        mv ~/android-sdk/cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest
        
        # Configura environment variables
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
        
        # Aceita licenças automaticamente
        yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses >/dev/null
        
        # Instala componentes Android necessários
        ~/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

    - name: Install Bubblewrap (Full Non-Interactive)
      run: |
        # Instala o Bubblewrap sem perguntas
        npm_config_yes=true npm install -g @bubblewrap/cli
        
        # Configura o Bubblewrap para não fazer perguntas
        mkdir -p ~/.bubblewrap
        echo '{"analyticsEnabled": false, "collectMetrics": false}' > ~/.bubblewrap/config.json
        
        # Verifica a instalação
        bubblewrap --version

    - name: Build APK (Forced Non-Interactive)
      run: |
        mkdir -p ./pwa-build
        cd ./pwa-build
        
        # Comando completo com todas as opções necessárias
        bubblewrap init \
          --manifest=https://${{ github.repository_owner }}.github.io/faq/manifest.json \
          --jdkPath=/usr/lib/jvm/zulu17-jdk-amd64 \
          --androidSdkPath=$ANDROID_HOME \
          --default \
          --non-interactive
        
        # Build com todas as validações desligadas
        bubblewrap build \
          --skipPwaValidation \
          --skipVersionCheck \
          --skipSigning
        
        if [ -f "app-release-unsigned.apk" ]; then
          mv app-release-unsigned.apk ../pwa-app.apk
          echo "APK gerado com sucesso!"
          ls -lh ../pwa-app.apk
        else
          echo "::error::Falha na geração do APK"
          ls -la
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pwa-apk
        path: pwa-app.apk
