name: Build PWA APK - Solução Definitiva Funcional

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java (JDK 17)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Android SDK (Correct Way)
      run: |
        # Estrutura exata que o Android SDK requer
        mkdir -p ~/android-sdk/cmdline-tools/latest
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d ~/android-sdk/cmdline-tools/latest
        mv ~/android-sdk/cmdline-tools/latest/cmdline-tools/* ~/android-sdk/cmdline-tools/latest/
        rm -rf ~/android-sdk/cmdline-tools/latest/cmdline-tools
        
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
        
        # Aceita licenças automaticamente
        yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses >/dev/null
        
        # Instala pacotes necessários
        ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME \
          "platform-tools" \
          "platforms;android-34" \
          "build-tools;34.0.0"

    - name: Install Bubblewrap (No Questions Asked)
      run: |
        npm install -g @bubblewrap/cli@1.9.0 --no-fund --no-audit --silent
        mkdir -p ~/.bubblewrap
        echo '{"analyticsEnabled": false, "nonInteractive": true}' > ~/.bubblewrap/config.json

    - name: Prepare Build Environment
      run: |
        mkdir -p ./pwa-build
        # Cria um arquivo de configuração completo
        cat > ./pwa-build/input-config.json <<EOL
        {
          "manifest": "https://${{ github.repository_owner }}.github.io/faq/manifest.json",
          "host": "${{ github.repository_owner }}.github.io",
          "path": "/faq/",
          "packageId": "com.pwa.faq",
          "appVersionName": "1.0.0",
          "appVersionCode": 1,
          "enableNotifications": false,
          "display": "standalone",
          "jdkPath": "$JAVA_HOME",
          "androidSdkPath": "$ANDROID_HOME"
        }
        EOL

    - name: Build APK (Forced Mode)
      run: |
        cd ./pwa-build
        
        # Comando completo com todos os parâmetros necessários
        bubblewrap init \
          --manifest=https://${{ github.repository_owner }}.github.io/faq/manifest.json \
          --jdkPath=$JAVA_HOME \
          --androidSdkPath=$ANDROID_HOME \
          --default \
          --nonInteractive=true \
          --host=${{ github.repository_owner }}.github.io \
          --path=/faq/ \
          --packageId=com.pwa.faq
        
        # Build com todas as validações desligadas
        bubblewrap build \
          --skipPwaValidation \
          --skipVersionCheck \
          --skipSigning
        
        if [ -f "app-release-unsigned.apk" ]; then
          mv app-release-unsigned.apk ../pwa-app.apk
          echo "✅ APK gerado com sucesso!"
          ls -lh ../pwa-app.apk
        else
          echo "::error::❌ Falha na geração do APK"
          echo "=== DEBUG INFO ==="
          ls -la
          bubblewrap doctor --verbose
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pwa-apk
        path: pwa-app.apk
